import { notFound } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { uccStatusLabel } from "@/lib/deals";
import PrintControls from "./PrintControls";

export const dynamic = "force-dynamic";

export default async function UccPrintPage({
  params,
}: {
  params: Promise<{ filingId: string }>;
}) {
  const { filingId } = await params;
  const supabase = await createClient();

  const { data: filing } = await supabase
    .from("ucc_filings")
    .select(
      "id, deal_id, filing_state, filing_number, debtor, secured_party, collateral_description, status, filed_at, created_at"
    )
    .eq("id", filingId)
    .maybeSingle();

  if (!filing) notFound();

  const { data: deal } = await supabase
    .from("deals")
    .select("name, target_entity")
    .eq("id", filing.deal_id)
    .maybeSingle();

  const isDraft = filing.status === "draft";

  return (
    <div className="min-h-screen bg-white text-black">
      <PrintControls backHref={`/command-dashboard/${filing.deal_id}`} />

      <div className="max-w-[8.5in] mx-auto p-8 md:p-12 print:p-0 print:max-w-none">
        {/* Header */}
        <div className="border-b-4 border-black pb-4 mb-6">
          <div className="text-xs uppercase tracking-widest text-neutral-500">
            {isDraft && "Draft — internal review only"}
            {filing.status === "filed" && "Filed record"}
            {filing.status === "amended" && "Amended filing"}
            {filing.status === "terminated" && "Terminated filing"}
          </div>
          <h1 className="text-3xl font-bold mt-1">UCC Financing Statement</h1>
          <div className="text-sm text-neutral-600 mt-2">
            State of filing: <span className="font-semibold">{filing.filing_state}</span>
            {filing.filing_number && (
              <>
                {" · "}Filing number:{" "}
                <span className="font-semibold">{filing.filing_number}</span>
              </>
            )}
            {filing.filed_at && (
              <>
                {" · "}Filed on:{" "}
                <span className="font-semibold">
                  {new Date(filing.filed_at).toLocaleDateString()}
                </span>
              </>
            )}
          </div>
        </div>

        {/* Related deal */}
        {deal && (
          <div className="mb-6 text-sm text-neutral-600">
            Related deal: <span className="font-semibold text-black">{deal.name}</span>
            {deal.target_entity && (
              <>
                {" · "}
                <span className="text-neutral-500">Target: {deal.target_entity}</span>
              </>
            )}
          </div>
        )}

        {/* Box 1: Debtor */}
        <Section number="1" title="Debtor's exact full legal name">
          <div className="text-lg font-medium">{filing.debtor}</div>
        </Section>

        {/* Box 2: Secured Party */}
        <Section number="2" title="Secured party's name">
          <div className="text-lg font-medium">{filing.secured_party}</div>
        </Section>

        {/* Box 3: Collateral */}
        <Section number="3" title="Collateral description">
          {filing.collateral_description ? (
            <p className="whitespace-pre-wrap leading-relaxed">
              {filing.collateral_description}
            </p>
          ) : (
            <p className="text-neutral-400 italic">
              (No collateral description provided — complete before filing.)
            </p>
          )}
        </Section>

        {/* Box 4: Status */}
        <Section number="4" title="Filing status">
          <div>{uccStatusLabel(filing.status)}</div>
        </Section>

        {/* Legal disclaimer */}
        <div className="mt-10 pt-4 border-t border-neutral-300 text-xs text-neutral-500 leading-relaxed">
          This document is{" "}
          {isDraft ? (
            <span className="font-semibold text-neutral-700">a draft generated by BPIS</span>
          ) : (
            "an internal record generated by BPIS"
          )}{" "}
          for operator review. An actual UCC-1 Financing Statement must be filed with the
          appropriate Secretary of State (or equivalent office) in accordance with UCC Article 9
          and that state's specific filing requirements. This document is not a substitute for
          the official UCC-1 form required by the filing office. Consult counsel before filing.
        </div>

        <div className="mt-6 text-xs text-neutral-400">
          Record created {new Date(filing.created_at).toLocaleString()}
        </div>
      </div>
    </div>
  );
}

function Section({
  number,
  title,
  children,
}: {
  number: string;
  title: string;
  children: React.ReactNode;
}) {
  return (
    <div className="border border-black mb-4">
      <div className="bg-neutral-100 border-b border-black px-3 py-1.5 text-xs uppercase tracking-wider font-semibold flex gap-3">
        <span className="text-neutral-500">Box {number}</span>
        <span>{title}</span>
      </div>
      <div className="p-4 min-h-[60px]">{children}</div>
    </div>
  );
}
